name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
          - arch: arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install zlib
    
    - name: Configure
      run: |
        ./configure --prefix=/opt/vios-binutils
    
    - name: Build
      run: |
        make -j$(nproc)
    
    - name: Test
      run: |
        make check || echo "Tests not yet implemented"
    
    - name: Create distribution
      if: matrix.arch == 'x86_64'
      run: |
        make install DESTDIR=$PWD/dist
        tar -czf vios-binutils-macos-${{ matrix.arch }}.tar.gz -C dist .
    
    - name: Upload artifacts
      if: matrix.arch == 'x86_64'
      uses: actions/upload-artifact@v4
      with:
        name: vios-binutils-macos-${{ matrix.arch }}
        path: vios-binutils-macos-${{ matrix.arch }}.tar.gz

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev
    
    - name: Configure
      run: |
        ./configure --prefix=/opt/vios-binutils
    
    - name: Build
      run: |
        make -j$(nproc)
    
    - name: Test
      run: |
        make check || echo "Tests not yet implemented"
    
    - name: Create distribution
      run: |
        make install DESTDIR=$PWD/dist
        tar -czf vios-binutils-linux-x86_64.tar.gz -C dist .
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vios-binutils-linux-x86_64
        path: vios-binutils-linux-x86_64.tar.gz

  test-homebrew-formula:
    runs-on: macos-latest
    needs: build-macos
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Homebrew formula syntax
      run: |
        brew install --build-from-source --formula ./Formula/vios-binutils.rb || echo "Formula test failed - this is expected for initial setup"

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vios-binutils-macos-x86_64/vios-binutils-macos-x86_64.tar.gz
          vios-binutils-linux-x86_64/vios-binutils-linux-x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
